"use client";
// // import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { UserProvider } from "@auth0/nextjs-auth0/client";
// import { SessionProvider } from "next-auth/react";

// import Navbar from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
//    pageProps: { session, ...pageProps },

// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//           <SessionProvider session={pageProps.session}>

//       <UserProvider>
//         <body className={inter.className}>
//           <Navbar />
//           {children}
//         </body>
//       </UserProvider>
//       </SessionProvider>

//     </html>
//   );
// }

// Ensure imports are properly set up based on your project structure

// Ensure imports are properly set up based on your project structure
// Ensure imports are properly set up based on your project structure
import { ReactNode } from "react";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Navbar from "@/components/Navbar";

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <title>My Application</title>
        {/* Add any other head tags here */}
      </head>
      <body>
        <UserProvider>
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
